[package]
name = "dna_transcribe"
version = "0.1.0"
authors = ["Kivanc Corut <kivanc.corut@uga.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
